

max-line-length: 120
test-warnings: false
doc-warnings: false
strictness: medium
ignore-paths:
  - docs
  - tests

bandit:
  run: false

mccabe:
  run: false

pyflakes:
  run: false

pycodestyle:
  disable:
    - E501

pylint:
  disable:
    - unsubscriptable-object
    - invalid-name
    - arguments-differ # to account for jobflow
    - logging-fstring-interpolation
    - arguments-renamed
    - assignment-from-none
    - unsupported-membership-test
    - cell-var-from-loop
    - broad-except
    - import-outside-toplevel
    - arguments_differ
    - duplicate-code
    - too-many-branches
    - too-many-statements
    - too-many-boolean-expressions
    - no-else-return
    - R0902
    - R0903
    - R0913
    - R0914
mypy:
  run: true
  options:
    ignore-missing-imports: true
    follow-imports: skip