site_name: pylattica documentation
site_description: Documentation for the pylattica package
copyright: Built by Max Gallant
watch:
  - src/pylattica
nav:
  - Home:
    - pylattica: index.md
    - Getting Started: ./guides/index.md
    - Reference: reference/core/lattice.md
    - Notebooks: ./examples/game_of_life.ipynb
    - Guides: ./guides/constructing_lattices.ipynb
  - Guides:
    - Getting Started: ./guides/index.md
    - Building Conway's Game Of Life: ./guides/game_of_life.ipynb
    - Lattices: ./guides/constructing_lattices.ipynb
    - Periodic Structures: ./guides/periodic_structures.ipynb
    - Neighborhoods: ./guides/neighborhoods.ipynb
    - Simulation States: ./guides/simulation_state.ipynb
    - Controllers and Update Rules: ./guides/controllers_and_update_rules.ipynb
    - Runners: ./guides/runners.ipynb
    - Square Grids: ./guides/square_grids.ipynb
    - Examples:
      - Life Like Demos: ./examples/life_like_demos.ipynb
  - Reference:
    - Core:
      - Runner:
        - SynchronousRunner: reference/core/runner/synchronous_runner.md
        - AsynchronousRunner: reference/core/runner/asynchronous_runner.md
      - PeriodicStructure: reference/core/periodic_structure.md
      - Lattice: reference/core/lattice.md
      - Coordinate Utilities: reference/core/coordinate_utils.md
      - Neighborhoods: reference/core/neighborhood.md
      - NeighborhoodBuilders: reference/core/neighborhood_builders.md
      - SimulationResult: reference/core/simulation_result.md
      - SimulationState: reference/core/simulation_state.md
      - Analyzer: reference/core/analyzer.md
      - BasicController: reference/core/basic_controller.md
      - DistanceMap: reference/core/distance_map.md
      - StructureBuilder: reference/core/structure_builder.md
      - Simulation: reference/core/simulation.md
    - Atomic:
      - PymatgenStructConverter: reference/atomic/pymatgen_struct_converter.md
    - Discrete:
      - DiscreteStepAnalyzer: reference/discrete/discrete_step_analyzer.md
      - DiscreteStateResultAnalyzer: reference/discrete/discrete_state_result_analyzer.md
      - PhaseSet: reference/discrete/phase_set.md
    - Structures:
      - SquareGrid:
        - GridSetup: reference/structures/square_grid/grid_setup.md
        - GrowthSetup: reference/structures/square_grid/growth_setup.md
        - Lattice: reference/structures/square_grid/lattice.md
        - Neighorboods: reference/structures/square_grid/neighborhoods.md
        - StructureBuilders: reference/structures/square_grid/structure_builders.md
      - Honeycomb:
        - Lattice: reference/structures/honeycomb/lattice.md
        - Neighorboods: reference/structures/honeycomb/neighborhoods.md
        - StructureBuilders: reference/structures/honeycomb/structure_builders.md
    - Visualization:
      - SquareGridArtist2D: reference/visualization/square_grid_artist_2D.md
      - SquareGridArtist3D: reference/visualization/square_grid_artist_3D.md
      - ResultArtist: reference/visualization/result_artist.md

repo_url: https://github.com/mcgalcode/pylattica/
repo_name: Github

theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple

# extra_css:
#   - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist

plugins:
  - search
  - section-index
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          paths: ['src']
          setup_commands:
            - import sys
            - sys.path.append("docs")
          selection:
            new_path_syntax: yes
