site_name: Reaction-network documentation
site_description: Documentation for the reaction-network package
copyright: Built by Matthew McDermott

# nav:
#   - Home: index.md
#   - CHANGELOG: CHANGELOG.md

repo_url: https://github.com/GENESIS-EFRC/reaction-network/
site_url: https://genesis-efrc.github.io/reaction-network/
repo_name: Github

theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist

plugins:
  - search
  - section-index
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
          selection:
            new_path_syntax: yes
      watch:
        - src/rxn_network