name: testing

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[strict,jupyter]'
          pip install black prospector[with_mypy]

      - name: Lint with black
        run: |
          black --check --diff --color src/pylattica

      - name: Lint with prospector
        run: |
          prospector src/pylattica

  test:
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest]
        python_version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[strict,tests]

      - name: Test with pytest
        run: |
          pytest --cov=src/pylattica --cov-report=xml

      - uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[strict,docs]

      - name: Build docs
        run: mkdocs build